name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      
      - name: setup node
        uses: actions/setup-node@v1
        with: 
          node-version: '12.x'

      - name: Create local changes
        run: |
          npm install
          node merge.js
      - name: Commit files
        run: |
          git config user.email acgstore25252@gmail.com
          git config user.name acg-store
          git add index.json
          git add 动漫/index.html
          git add 动漫/index.json
          git add 漫画/index.html
          git add 漫画/index.json
          git add 阅读/index.html
          git add 阅读/index.json
          git add 有声/index.html
          git add 有声/index.json
          git commit -m "merge all site" -a
          git push origin main
