name: CI
on:
  push:
    branches: [ node ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      
      - name: setup node
        uses: actions/setup-node@v1
        with: 
          node-version: '12.x'

      - name: Create local changes
        run: |
          npm install
          node merge.js
      - name: Commit files
        run: |
          git config user.email acgstore25252@gmail.com
          git config user.name acg-store
          git checkout main
          git add 动漫/*.html
          git add 漫画/*.html
          git add 阅读/*.html
          git add 有声/*.html
          git commit -m "merge" -a
          git push origin main     
